stages:
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SPACETIME18_DEPLOY_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - ssh-keyscan github.com >> ~/.ssh/known_hosts

deploy:
  stage: deploy
  script:
    - if ! git remote | grep github; then git remote add github git@github.com:nrm/spacetime18.git; fi
    # - git push --force github master_in_progress
    - if git show-ref --verify --quiet refs/heads/master_in_progress; then git push --force github master_in_progress; else echo "Branch 'master_in_progress' does not exist."; fi
  only:
    - master_in_progress
