stages:
  - deploy
  - test
  - collect

# after_script:
#   - rm -rf result_job*

variables:
  GIT_SUBMODULE_STRATEGY: recursive

deploy:
  stage: deploy
  script:
    - git checkout master_in_progress
    - git pull origin master_in_progress
    - if ! git remote | grep github; then git remote add github git@github.com:nrm/spacetime18.git; fi
    - git push --force github master_in_progress
  when: manual
  only:
    - master_in_progress

execute-job-1:
  stage: test
  script:
    - echo "Executing test 1..."
    - mkdir -p result_job1
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job1.csv"
    # - echo "Result file will be: $RESULT_FILE"
    - bash ./run_test_L.1.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-06-15.tif
    - mv result*.csv result_job1/
  artifacts:
    paths:
      - result_job1/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-2:
  stage: test
  script:
    - echo "Executing test 2..."
    - mkdir -p result_job2
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job2.csv"
    # - echo "Result file will be: $RESULT_FILE"
    - bash ./run_test_L.2.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-06-15.tif
    - mv result*.csv result_job2/
  artifacts:
    paths:
      - result_job2/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-3:
  stage: test
  script:
    - echo "Executing test 3..."
    - mkdir -p result_job3
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job3.csv"
    # - echo "Result file will be: $RESULT_FILE"
    - bash ./run_test_L.1.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-08-16.tif
    - mv result*.csv result_job3/
  artifacts:
    paths:
      - result_job3/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-4:
  stage: test
  script:
    - echo "Executing test 4..."
    - mkdir -p result_job4
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job4.csv"
    # - echo "Result file will be: $RESULT_FILE"
    - bash ./run_test_L.2.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-08-16.tif
    - mv result*.csv result_job4/
  artifacts:
    paths:
      - result_job4/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-5:
  stage: test
  script:
    - echo "Executing test 5..."
    - mkdir -p result_job5
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job5.csv"
    # - echo "Result file will be: $RESULT_FILE"
    - bash ./run_test_L.1.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-10-10.tif
    - mv result*.csv result_job5/
  artifacts:
    paths:
      - result_job5/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-6:
  stage: test
  script:
    - echo "Executing test 6..."
    - mkdir -p result_job6
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job6.csv"
    # - echo "Result file will be: $RESULT_FILE"
    - bash ./run_test_L.2.sh  "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-10-10.tif
    - mv result*.csv result_job6/
  artifacts:
    paths:
      - result_job6/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-7:
  stage: test
  script:
    - echo "Executing test 7..."
    - mkdir -p result_job7
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job7.csv"
    # - echo "Result file will be: $RESULT_FILE"
    - bash ./run_test_L.1.sh  "$RESULT_FILE" /opt/spacetime/layouts/layout_2022-03-17.tif
    - mv result*.csv result_job7/
  artifacts:
    paths:
      - result_job7/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-8:
  stage: test
  script:
    - echo "Executing test 8..."
    - mkdir -p result_job8
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job8.csv"
    # - echo "Result file will be: $RESULT_FILE"
    - bash ./run_test_L.2.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2022-03-17.tif
    - mv result*.csv result_job8/
  artifacts:
    paths:
      - result_job8/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-9:
  stage: test
  script:
    - echo "Executing test 9..."
    - mkdir -p result_job9
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job9.csv"
    # - echo "Result file will be: $RESULT_FILE"
    - bash ./run_test_L.3.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-06-15.tif
    - mv result*.csv result_job9/
  artifacts:
    paths:
      - result_job9/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-10:
  stage: test
  script:
    - echo "Executing test 10..."
    - mkdir -p result_job10
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job10.csv"
    # - echo "Result file will be: $RESULT_FILE"
    - bash ./run_test_L.4.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-06-15.tif
    - mv result*.csv result_job10/
  artifacts:
    paths:
      - result_job10/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-11:
  stage: test
  script:
    - echo "Executing test 11..."
    - mkdir -p result_job11
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job11.csv"
    # - echo "Result file will be: $RESULT_FILE"
    - bash ./run_test_L.3.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-08-16.tif
    - mv result*.csv result_job11/
  artifacts:
    paths:
      - result_job11/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-12:
  stage: test
  script:
    - echo "Executing test 12..."
    - mkdir -p result_job12
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job12.csv"
    - bash ./run_test_L.4.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-08-16.tif
    - mv result*.csv result_job12/
  artifacts:
    paths:
      - result_job12/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-13:
  stage: test
  script:
    - echo "Executing test 13..."
    - mkdir -p result_job13
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job13.csv"
    - bash ./run_test_L.3.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-10-10.tif
    - mv result*.csv result_job13/
  artifacts:
    paths:
      - result_job13/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-14:
  stage: test
  script:
    - echo "Executing test 14..."
    - mkdir -p result_job14
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job14.csv"
    - bash ./run_test_L.4.sh  "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-10-10.tif
    - mv result*.csv result_job14/
  artifacts:
    paths:
      - result_job14/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-15:
  stage: test
  script:
    - echo "Executing test 15..."
    - mkdir -p result_job15
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job15.csv"
    - bash ./run_test_L.3.sh  "$RESULT_FILE" /opt/spacetime/layouts/layout_2022-03-17.tif
    - mv result*.csv result_job15/
  artifacts:
    paths:
      - result_job15/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-16:
  stage: test
  script:
    - echo "Executing test 16..."
    - mkdir -p result_job16
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_job16.csv"
    - bash ./run_test_L.4.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2022-03-17.tif
    - mv result*.csv result_job16/
  artifacts:
    paths:
      - result_job16/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'


collect-results:
  stage: collect
  script:
    - rm -rf combined_results || echo "No exist dir"
    - mkdir -p combined_results
    - echo "layout_name;crop_name;ul;ur;br;bl;crs;start;end" > combined_results/combined_result.csv
    - cp result_job?/result_${CI_COMMIT_SHORT_SHA}_job?.csv combined_results/ || echo "No results from job 1"
    - echo "Processing combined results..."
    - grep -v "layout_name" result_job*/result_${CI_COMMIT_SHORT_SHA}_job*.csv |  cut -d':' -f2- >> combined_results/combined_result.csv
    - ls -R combined_results/
    # Здесь можно добавить дополнительные команды для обработки результатов
  artifacts:
    paths:
      - combined_results/
    expire_in: 1 week
  needs:
    - execute-job-1
    - execute-job-2
    - execute-job-3
    - execute-job-4
    - execute-job-5
    - execute-job-6
    - execute-job-7
    - execute-job-8
    - execute-job-9
    - execute-job-10
    - execute-job-11
    - execute-job-12
    - execute-job-13
    - execute-job-14
    - execute-job-15
    - execute-job-16


execute-syntjob-1:
  stage: synttest
  script:
    - echo "Executing test 1..."
    - mkdir -p result_syntjob1
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob1.csv"
    - bash ./run_synt_test_L.1.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-06-15.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob1/
  artifacts:
    paths:
      - result_syntjob1/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-2:
  stage: synttest
  script:
    - echo "Executing test 2..."
    - mkdir -p result_syntjob2
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob2.csv"
    - bash ./run_synt_test_L.2.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-06-15.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob2/
  artifacts:
    paths:
      - result_syntjob2/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-3:
  stage: synttest
  script:
    - echo "Executing test 3..."
    - mkdir -p result_syntjob3
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob3.csv"
    - bash ./run_synt_test_L.1.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-08-16.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob3/
  artifacts:
    paths:
      - result_syntjob3/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-4:
  stage: synttest
  script:
    - echo "Executing test 4..."
    - mkdir -p result_syntjob4
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob4.csv"
    - bash ./run_synt_test_L.2.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-08-16.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob4/
  artifacts:
    paths:
      - result_syntjob4/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-5:
  stage: synttest
  script:
    - echo "Executing test 5..."
    - mkdir -p result_syntjob5
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob5.csv"
    - bash ./run_synt_test_L.1.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-10-10.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob5/
  artifacts:
    paths:
      - result_syntjob5/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-6:
  stage: synttest
  script:
    - echo "Executing test 6..."
    - mkdir -p result_syntjob6
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob6.csv"
    - bash ./run_synt_test_L.2.sh  "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-10-10.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob6/
  artifacts:
    paths:
      - result_syntjob6/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-7:
  stage: synttest
  script:
    - echo "Executing test 7..."
    - mkdir -p result_syntjob7
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob7.csv"
    - bash ./run_synt_test_L.1.sh  "$RESULT_FILE" /opt/spacetime/layouts/layout_2022-03-17.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob7/
  artifacts:
    paths:
      - result_syntjob7/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-8:
  stage: synttest
  script:
    - echo "Executing test 8..."
    - mkdir -p result_syntjob8
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob8.csv"
    - bash ./run_synt_test_L.2.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2022-03-17.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob8/
  artifacts:
    paths:
      - result_syntjob8/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-9:
  stage: synttest
  script:
    - echo "Executing test 9..."
    - mkdir -p result_syntjob9
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob9.csv"
    - bash ./run_synt_test_L.3.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-06-15.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob9/
  artifacts:
    paths:
      - result_syntjob9/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-10:
  stage: synttest
  script:
    - echo "Executing test 10..."
    - mkdir -p result_syntjob10
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob10.csv"
    - bash ./run_synt_test_L.4.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-06-15.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob10/
  artifacts:
    paths:
      - result_syntjob10/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-11:
  stage: synttest
  script:
    - echo "Executing test 11..."
    - mkdir -p result_syntjob11
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob11.csv"
    - bash ./run_synt_test_L.3.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-08-16.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob11/
  artifacts:
    paths:
      - result_syntjob11/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-12:
  stage: synttest
  script:
    - echo "Executing test 12..."
    - mkdir -p result_syntjob12
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob12.csv"
    - bash ./run_synt_test_L.4.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-08-16.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob12/
  artifacts:
    paths:
      - result_syntjob12/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-13:
  stage: synttest
  script:
    - echo "Executing test 13..."
    - mkdir -p result_syntjob13
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob13.csv"
    - bash ./run_synt_test_L.3.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-10-10.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob13/
  artifacts:
    paths:
      - result_syntjob13/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-14:
  stage: synttest
  script:
    - echo "Executing test 14..."
    - mkdir -p result_syntjob14
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob14.csv"
    - bash ./run_synt_test_L.4.sh  "$RESULT_FILE" /opt/spacetime/layouts/layout_2021-10-10.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob14/
  artifacts:
    paths:
      - result_syntjob14/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-15:
  stage: synttest
  script:
    - echo "Executing test 15..."
    - mkdir -p result_syntjob15
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob15.csv"
    - bash ./run_synt_test_L.3.sh  "$RESULT_FILE" /opt/spacetime/layouts/layout_2022-03-17.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob15/
  artifacts:
    paths:
      - result_syntjob15/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

execute-syntjob-16:
  stage: synttest
  script:
    - echo "Executing test 16..."
    - mkdir -p result_syntjob16
    - RESULT_FILE="result_${CI_COMMIT_SHORT_SHA}_syntjob16.csv"
    - bash ./run_synt_test_L.4.sh "$RESULT_FILE" /opt/spacetime/layouts/layout_2022-03-17.tif "project_${CI_COMMIT_SHORT_SHA}"
    - mv result*.csv result_syntjob16/
  artifacts:
    paths:
      - result_syntjob16/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_synttest.*/'

collect-syntresults:
  stage: syntcollect
  script:
    - rm -rf combined_syntresults || echo "No exist dir"
    - mkdir -p combined_syntresults
    - echo "layout_name;crop_name;ul;ur;br;bl;crs;start;end" > combined_syntresults/combined_syntresult.csv
    - cp result_syntjob?/result_${CI_COMMIT_SHORT_SHA}_syntjob?.csv combined_syntresults/ || echo "No results from job 1"
    - echo "Processing combined results..."
    - grep -v "layout_name" result_syntjob*/result_${CI_COMMIT_SHORT_SHA}_syntjob*.csv |  cut -d':' -f2- >> combined_syntresults/combined_syntresult.csv
    - ls -R combined_syntresults/
  artifacts:
    paths:
      - combined_syntresults/
    expire_in: 1 week
  needs:
    - execute-syntjob-1
    - execute-syntjob-2
    - execute-syntjob-3
    - execute-syntjob-4
    - execute-syntjob-5
    - execute-syntjob-6
    - execute-syntjob-7
    - execute-syntjob-8
    - execute-syntjob-9
    - execute-syntjob-10
    - execute-syntjob-11
    - execute-syntjob-12
    - execute-syntjob-13
    - execute-syntjob-14
    - execute-syntjob-15
    - execute-syntjob-16
