stages:
  - deploy
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SPACETIME18_DEPLOY_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - ssh-keyscan github.com >> ~/.ssh/known_hosts

deploy:
  stage: deploy
  script:
    - git checkout master_in_progress
    - git pull origin master_in_progress
    - if ! git remote | grep github; then git remote add github git@github.com:nrm/spacetime18.git; fi
    - git push --force github master_in_progress
  when: manual
  only:
    - master_in_progress

test:
  stage: test
  before_script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - source venv/bin/activate
    - python3 test.py --layout /home/spacetime/spacetime18/layouts/layout_2021-08-16.tif --crop /home/spacetime/spacetime18/1_20/crop_0_0_0000.tif
  artifacts:
    paths:
      - result.csv
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'
