stages:
  - deploy
  - test
  - collect

# after_script:
#   - rm -rf result_job*

variables:
  GIT_SUBMODULE_STRATEGY: recursive

deploy:
  stage: deploy
  script:
    - git checkout master_in_progress
    - git pull origin master_in_progress
    - if ! git remote | grep github; then git remote add github git@github.com:nrm/spacetime18.git; fi
    - git push --force github master_in_progress
  when: manual
  only:
    - master_in_progress

execute-job-1:
  stage: test
  script:
    - echo "Executing test 1..."
    - mkdir -p result_job1
    - bash ./run_test_L.1.sh result_${CI_COMMIT_SHORT_SHA}_job1 /opt/spacetime/layouts/layout_2021-06-15.tif
    - mv result*.csv result_job1/
  artifacts:
    paths:
      - result_job1/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-2:
  stage: test
  script:
    - echo "Executing test 2..."
    - mkdir -p result_job2
    # - bash ./run_test_L.2.sh $CI_COMMIT_SHORT_SHA /opt/spacetime/layouts/layout_2021-06-15.tif
    - bash ./run_test_L.2.sh result_${CI_COMMIT_SHORT_SHA}_job2 /opt/spacetime/layouts/layout_2021-06-15.tif
    - mv result*.csv result_job2/
  artifacts:
    paths:
      - result_job2/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-3:
  stage: test
  script:
    - echo "Executing test 3..."
    - mkdir -p result_job3
    - bash ./run_test_L.1.sh result_${CI_COMMIT_SHORT_SHA}_job3 /opt/spacetime/layouts/layout_2021-08-16.tif
    - mv result*.csv result_job3/
  artifacts:
    paths:
      - result_job3/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-4:
  stage: test
  script:
    - echo "Executing test 4..."
    - mkdir -p result_job4
    - bash ./run_test_L.2.sh result_${CI_COMMIT_SHORT_SHA}_job4 /opt/spacetime/layouts/layout_2021-08-16.tif
    - mv result*.csv result_job4/
  artifacts:
    paths:
      - result_job4/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-5:
  stage: test
  script:
    - echo "Executing test 5..."
    - mkdir -p result_job5
    - bash ./run_test_L.1.sh result_${CI_COMMIT_SHORT_SHA}_job5 $CI_COMMIT_SHORT_SHA /opt/spacetime/layouts/layout_2021-10-10.tif
    - mv result*.csv result_job5/
  artifacts:
    paths:
      - result_job5/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-6:
  stage: test
  script:
    - echo "Executing test 6..."
    - mkdir -p result_job6
    - bash ./run_test_L.2.sh  result_${CI_COMMIT_SHORT_SHA}_job6 /opt/spacetime/layouts/layout_2021-10-10.tif
    - mv result*.csv result_job6/
  artifacts:
    paths:
      - result_job6/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-7:
  stage: test
  script:
    - echo "Executing test 7..."
    - mkdir -p result_job7
    - bash ./run_test_L.1.sh  result_${CI_COMMIT_SHORT_SHA}_job7 /opt/spacetime/layouts/layout_2022-03-17.tif
    - mv result*.csv result_job7/
  artifacts:
    paths:
      - result_job7/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

execute-job-8:
  stage: test
  script:
    - echo "Executing test 8..."
    - mkdir -p result_job8
    - bash ./run_test_L.2.sh  result_${CI_COMMIT_SHORT_SHA}_job8 /opt/spacetime/layouts/layout_2022-03-17.tif
    - mv result*.csv result_job8/
  artifacts:
    paths:
      - result_job8/
    expire_in: 1 week
  timeout: 4h
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /.*run_test.*/'

collect-results:
  stage: collect
  script:
    - rm -rf combined_results || echo "No exist dir"
    - mkdir -p combined_results
    - echo "layout_name;crop_name;ul;ur;br;bl;crs;start;end" > combined_results/combined_result.csv
    - echo "Collecting results from job 1..."
    - cp result_job?/result_${CI_COMMIT_SHORT_SHA}_job?.csv combined_results/ || echo "No results from job 1"
    - grep -v "layout_name" result_job*/result_${CI_COMMIT_SHORT_SHA}_job*.csv >> combined_results/combined_result.csv
    # # - grep -v "layout_name" result_job1/result_${CI_COMMIT_SHORT_SHA}_job1.csv >> combined_results/combined_result.csv
    # - echo "Collecting results from job 2..."
    # - cp result_job2/result_${CI_COMMIT_SHORT_SHA}_job2.csv combined_results/ || echo "No results from job 2"
    # # - grep -v "layout_name" result_job2/result_${CI_COMMIT_SHORT_SHA}_job2.csv >> combined_results/combined_result.csv
    # - echo "Collecting results from job 3..."
    # - cp result_job3/result_${CI_COMMIT_SHORT_SHA}_job3.csv combined_results/ || echo "No results from job 3"
    # # - grep -v "layout_name" result_job3/result_${CI_COMMIT_SHORT_SHA}_job3.csv >> combined_results/combined_result.csv
    # - echo "Collecting results from job 4..."
    # - cp result_job4/result_${CI_COMMIT_SHORT_SHA}_job4.csv combined_results/ || echo "No results from job 4"
    # # - grep -v "layout_name" result_job4/*.csv >> combined_results/combined_result.csv
    # - echo "Collecting results from job 5..."
    # - cp result_job5/result_${CI_COMMIT_SHORT_SHA}_job5.csv combined_results/ || echo "No results from job 5"
    # # - grep -v "layout_name" result_job5/*.csv >> combined_results/combined_result.csv
    # - echo "Collecting results from job 6..."
    # - cp result_job6/* combined_results/ || echo "No results from job 6"
    # - grep -v "layout_name" result_job6/*.csv >> combined_results/combined_result.csv
    # - echo "Collecting results from job 7..."
    # - cp result_job7/* combined_results/ || echo "No results from job 7"
    # - grep -v "layout_name" result_job7/*.csv >> combined_results/combined_result.csv
    # - echo "Collecting results from job 8..."
    # - cp result_job8/* combined_results/ || echo "No results from job 8"
    # - grep -v "layout_name" result_job*/result_${CI_COMMIT_SHORT_SHA}_job*.csv >> combined_results/combined_result.csv
    - echo "Processing combined results..."
    - ls -R combined_results/
    # Здесь можно добавить дополнительные команды для обработки результатов
  artifacts:
    paths:
      - combined_results/
    expire_in: 1 week
  needs:
    - execute-job-1
    - execute-job-2
    - execute-job-3
    - execute-job-4
    - execute-job-5
    - execute-job-6
    - execute-job-7
    - execute-job-8
