version: '3.9'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ../layouts/:/layouts
    environment:
      - LAYOUTS_DIR=/layouts
